name: Create Azure Container Registry with ARM Template
on:
  workflow_dispatch:
    inputs:
       ACRName:
        description: ACR Name
        type: string
        required: true
       ACRLocation:
         description: ACR Location
         type: string
         required: true
       ACRSku:
         description: ACR Sku
         type: string
         required: true
    
      
jobs:
  create-acr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy ACR with ARM Template
        uses: azure/arm-deploy@v1.0.9
        with:
          subscriptionId: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          template: "./registry.json"
          ResourceGroupName: "my-resource" 
          parameters: ./para.json registryName=${{ inputs.ACRName }} registryLocation=${{ inputs.ACRLocation }} registrySku=${{ inputs.ACRSku }} 
